<a href="https://colab.research.google.com/github/Nitin286roxs/NLP/blob/main/word_embedding_technique_tensorflow/word_embedding_technique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word Embedding Technique using Embedding layer in Keras

In [3]:
!pip install tensorflow

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
voc_size=10000

## One Hot Representaion

In [7]:
one_hot_repr=[one_hot(word, voc_size) for word in sent]

In [8]:
one_hot_repr

[[9268, 4053, 1467, 6093],
 [9268, 4053, 1467, 2942],
 [9268, 1380, 1467, 738],
 [8632, 5049, 4954, 8132, 314],
 [8632, 5049, 4954, 8132, 3959],
 [5097, 9268, 7648, 1467, 2891],
 [2842, 3188, 6663, 8132]]

## word embedding Representation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [12]:
#prepadding
sent_length=8
embedding_docs=pad_sequences(one_hot_repr, padding="pre", maxlen=sent_length)
print(embedding_docs)

[[   0    0    0    0 9268 4053 1467 6093]
 [   0    0    0    0 9268 4053 1467 2942]
 [   0    0    0    0 9268 1380 1467  738]
 [   0    0    0 8632 5049 4954 8132  314]
 [   0    0    0 8632 5049 4954 8132 3959]
 [   0    0    0 5097 9268 7648 1467 2891]
 [   0    0    0    0 2842 3188 6663 8132]]


In [13]:
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size, 10,))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embedding_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[ 0.00919211, -0.0283743 ,  0.03042312, -0.0383703 ,  0.04473658,
        -0.04730289,  0.02210548, -0.03764423,  0.01366417,  0.0433916 ],
       [ 0.00919211, -0.0283743 ,  0.03042312, -0.0383703 ,  0.04473658,
        -0.04730289,  0.02210548, -0.03764423,  0.01366417,  0.0433916 ],
       [ 0.00919211, -0.0283743 ,  0.03042312, -0.0383703 ,  0.04473658,
        -0.04730289,  0.02210548, -0.03764423,  0.01366417,  0.0433916 ],
       [ 0.00919211, -0.0283743 ,  0.03042312, -0.0383703 ,  0.04473658,
        -0.04730289,  0.02210548, -0.03764423,  0.01366417,  0.0433916 ],
       [ 0.04330278, -0.01547893, -0.04174298, -0.02998015,  0.03857004,
         0.04291648,  0.03277398, -0.04902012,  0.0082822 ,  0.04040052],
       [-0.0143897 , -0.02958556, -0.02501988,  0.02287379,  0.04393986,
        -0.03351156, -0.03240805, -0.01488215,  0.03481628, -0.02124903],
       [-0.02455353, -0.01461627,  0.01946695, -0.01297544, -0.04035844,
         0.02347134, -0.02321175, -0.03071954